<Demo>:
    name: name
    age: age
    cons:1
    rows:5

    Lable:
        text: "Enter your name"
        font_size: 50
    TextInput:
        id:name
        text:""   
        font_size: 50
    
    Lable:
        text: "Enter your age"
        font_size: 50

    TextInput:
        id: age
        text:""    
        font_size: 50  

    Button:
        text:"submit"
        font_size: 50  
        on_press : root.on_click   


        
         